models:
#  - name: gpt-4o
#    description: "GPT-4o"
  - name: gpt-4o-mini
    description: "GPT-4o Mini"
  - name: ollama/mixtral:8x7b
    description: "Mixtral 8x7B"
    provider: ollama
  - name: ollama/llama3.2:1b
    description: "Llama 3.2 1B"
    provider: ollama
  - name: ollama/llama3.2:latest
    description: "Llama 3.2 3B"
    provider: ollama
  - name: ollama/qwen2.5:7b
    description: "Qwen2.5 7B"
    provider: ollama
#  - name: ollama/qwen2.5:14b
#    description: "Qwen2.5 14B"
#    provider: ollama
  - name: ollama/deepseek-r1:1.5b
    description: "DeepSeek-R1-Distill-Qwen-1.5B"
    provider: ollama
  - name: ollama/deepseek-r1:7b
    description: "DeepSeek-R1-Distill-Qwen-7B"
    provider: ollama
  - name: ollama/deepseek-r1:8b
    description: "DeepSeek-R1-Distill-Llama-8B"
    provider: ollama
  #- name: ollama/deepseek-r1:14b
  #  description: "DeepSeek R1 14B"
  #  provider: ollama

metrics:
  - name: hallucination
    enabled: true
  - name: answer_relevance
    enabled: true
  - name: g_eval_summary
    enabled: true
    description: "Evaluates summary quality using G-Eval" 