models:
  - name: gpt-4o
    description: "GPT-4o"
  - name: gpt-4o-mini
    description: "GPT-4o Mini"
  - name: ollama/llama3.2:latest
    description: "Llama 3.2 3B"
    provider: ollama
  - name: ollama/deepseek-r1:14b
    description: "DeepSeek R1 14B"
    provider: ollama

metrics:
  - name: hallucination
    enabled: true
  - name: answer_relevance
    enabled: true 